#!/bin/bash
default_branch=$1

if [[ -z ${default_branch} ]]; then
  default_branch=$(git symbolic-ref -q refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
fi

if [[ -z ${default_branch} ]]; then
  echo "Unable to find the default branch."
  echo "The current branch might be in detached HEAD state or you are already on it."
  echo "If you are not on the default branch, try to use the command 'gh clear default-branch-name'"
  exit 1
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)
uncommitted_changes=$(git status --porcelain=v1 2>/dev/null | wc -l)

if [[ ${uncommitted_changes} -ne 0 ]]; then
  echo "There are uncommitted changes that will be lost in your branch"
  git status
  exit 1
fi

echo "Default branch: ${default_branch}"
if [[ "${current_branch}" != "${default_branch}" ]]; then
   echo "Current branch: ${current_branch}"
   git checkout ${default_branch} && git pull && git branch -d ${current_branch}
fi
